# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-27 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 7, 38, 39, 633009, tzinfo=utc)),
        ),
    ]
