# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-27 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20210127_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 8, 15, 45, 505665, tzinfo=utc)),
        ),
    ]
