# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-27 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_auto_20210127_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 17, 45, 38, 988515, tzinfo=utc)),
        ),
    ]
